name: Github Actions Example

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ develop ]

jobs:
  build:

    name: Building Github Workflow
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: yarn ci
    - run: yarn run build --if-present
    - run: yarn test
