name: First Github Workflow

on:
    pull_request:
        branches:
            - master
    push:
        branches:
            - develop

jobs:
    build:
        name: Building Github Workflow
        runs-on: macos-lastest

    steps:
        - uses: actions/checkout@v1
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v1
          with: actions/setup-node@v1
              node-version: ${{ matrix.node-version }}
        - name: yarn install, build, and test
          run: |
              yarn ci
              yarn build --if-present
              yarn test
          env:
              CI: true
